CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Role" integer NOT NULL,
        "UniversityId" uuid,
        "CohortId" uuid,
        "StudentId" uuid,
        "Status" integer NOT NULL,
        "InviteToken" text,
        "InviteTokenExpiry" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Programmes" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Description" text NOT NULL,
        "DurationYears" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Programmes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Students" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Students" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Universities" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Domain" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Universities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "ProgrammeYears" (
        "Id" uuid NOT NULL,
        "ProgrammeId" uuid NOT NULL,
        "YearNumber" integer NOT NULL,
        "Name" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProgrammeYears" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProgrammeYears_Programmes_ProgrammeId" FOREIGN KEY ("ProgrammeId") REFERENCES "Programmes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Certificates" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ProgrammeId" uuid NOT NULL,
        "CertificateNumber" text NOT NULL,
        "IssuedAt" timestamp with time zone NOT NULL,
        "PdfBlobUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Certificates_Programmes_ProgrammeId" FOREIGN KEY ("ProgrammeId") REFERENCES "Programmes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Certificates_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Cohorts" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "ProgrammeId" uuid NOT NULL,
        "Name" text NOT NULL,
        "IntakeYear" integer NOT NULL,
        "CurrentYear" integer NOT NULL,
        "CurrentSemester" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Cohorts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cohorts_Programmes_ProgrammeId" FOREIGN KEY ("ProgrammeId") REFERENCES "Programmes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Cohorts_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "UniversityProgrammes" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "ProgrammeId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_UniversityProgrammes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UniversityProgrammes_Programmes_ProgrammeId" FOREIGN KEY ("ProgrammeId") REFERENCES "Programmes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UniversityProgrammes_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Semesters" (
        "Id" uuid NOT NULL,
        "ProgrammeYearId" uuid NOT NULL,
        "SemesterNumber" integer NOT NULL,
        "Name" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Semesters" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Semesters_ProgrammeYears_ProgrammeYearId" FOREIGN KEY ("ProgrammeYearId") REFERENCES "ProgrammeYears" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "StudentEnrolments" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "CohortId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "ActivatedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_StudentEnrolments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StudentEnrolments_Cohorts_CohortId" FOREIGN KEY ("CohortId") REFERENCES "Cohorts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StudentEnrolments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StudentEnrolments_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Modules" (
        "Id" uuid NOT NULL,
        "SemesterId" uuid NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Description" text NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Modules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Modules_Semesters_SemesterId" FOREIGN KEY ("SemesterId") REFERENCES "Semesters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Lessons" (
        "Id" uuid NOT NULL,
        "ModuleId" uuid NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Description" text NOT NULL,
        "Status" integer NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedByUserId" text,
        "DurationSeconds" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Lessons_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "ModulePrerequisites" (
        "Id" uuid NOT NULL,
        "ModuleId" uuid NOT NULL,
        "PrerequisiteModuleId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ModulePrerequisites" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModulePrerequisites_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ModulePrerequisites_Modules_PrerequisiteModuleId" FOREIGN KEY ("PrerequisiteModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "ModuleProgresses" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ModuleId" uuid NOT NULL,
        "ProgressPercent" integer NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ModuleProgresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModuleProgresses_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ModuleProgresses_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "OfflineAssessmentResults" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ModuleId" uuid NOT NULL,
        "AssessmentType" text NOT NULL,
        "ScorePercent" integer NOT NULL,
        "Passed" boolean NOT NULL,
        "Notes" text,
        "EnteredByUserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_OfflineAssessmentResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OfflineAssessmentResults_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OfflineAssessmentResults_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "Quizzes" (
        "Id" uuid NOT NULL,
        "ModuleId" uuid NOT NULL,
        "Title" text NOT NULL,
        "PassPercentage" integer NOT NULL,
        "TimeLimitMinutes" integer NOT NULL,
        "MaxAttempts" integer NOT NULL,
        "CooldownHours" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Quizzes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Quizzes_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "ContentPublications" (
        "Id" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "UniversityId" uuid,
        "PublishedAt" timestamp with time zone NOT NULL,
        "PublishedByUserId" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ContentPublications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContentPublications_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ContentPublications_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "LessonAssets" (
        "Id" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "AssetType" integer NOT NULL,
        "FileName" text NOT NULL,
        "BlobUrl" text NOT NULL,
        "ContentType" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LessonAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LessonAssets_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "LessonProgresses" (
        "Id" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "ProgressPercent" integer NOT NULL,
        "WatchedSeconds" integer NOT NULL,
        "CompletedAt" timestamp with time zone,
        "LastActivityAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LessonProgresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LessonProgresses_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LessonProgresses_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "QuizAttempts" (
        "Id" uuid NOT NULL,
        "QuizId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "ScorePercent" integer NOT NULL,
        "Passed" boolean NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "SubmittedAt" timestamp with time zone,
        "AttemptNumber" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_QuizAttempts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuizAttempts_Quizzes_QuizId" FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuizAttempts_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "QuizQuestions" (
        "Id" uuid NOT NULL,
        "QuizId" uuid NOT NULL,
        "QuestionText" text NOT NULL,
        "SortOrder" integer NOT NULL,
        "Points" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_QuizQuestions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuizQuestions_Quizzes_QuizId" FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "QuizOptions" (
        "Id" uuid NOT NULL,
        "QuestionId" uuid NOT NULL,
        "OptionText" text NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_QuizOptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuizOptions_QuizQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "QuizQuestions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE TABLE "QuizAnswers" (
        "Id" uuid NOT NULL,
        "AttemptId" uuid NOT NULL,
        "QuestionId" uuid NOT NULL,
        "SelectedOptionId" uuid NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_QuizAnswers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuizAnswers_QuizAttempts_AttemptId" FOREIGN KEY ("AttemptId") REFERENCES "QuizAttempts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuizAnswers_QuizOptions_SelectedOptionId" FOREIGN KEY ("SelectedOptionId") REFERENCES "QuizOptions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_QuizAnswers_QuizQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "QuizQuestions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON "AspNetUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Certificates_CertificateNumber" ON "Certificates" ("CertificateNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Certificates_ProgrammeId" ON "Certificates" ("ProgrammeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Certificates_StudentId" ON "Certificates" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Cohorts_ProgrammeId" ON "Cohorts" ("ProgrammeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Cohorts_UniversityId_Name" ON "Cohorts" ("UniversityId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_ContentPublications_LessonId_UniversityId" ON "ContentPublications" ("LessonId", "UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_ContentPublications_UniversityId" ON "ContentPublications" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_LessonAssets_LessonId" ON "LessonAssets" ("LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_LessonProgresses_LessonId" ON "LessonProgresses" ("LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LessonProgresses_StudentId_LessonId" ON "LessonProgresses" ("StudentId", "LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Lessons_ModuleId" ON "Lessons" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ModulePrerequisites_ModuleId_PrerequisiteModuleId" ON "ModulePrerequisites" ("ModuleId", "PrerequisiteModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_ModulePrerequisites_PrerequisiteModuleId" ON "ModulePrerequisites" ("PrerequisiteModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_ModuleProgresses_ModuleId" ON "ModuleProgresses" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ModuleProgresses_StudentId_ModuleId" ON "ModuleProgresses" ("StudentId", "ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Modules_SemesterId" ON "Modules" ("SemesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_OfflineAssessmentResults_ModuleId" ON "OfflineAssessmentResults" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_OfflineAssessmentResults_StudentId" ON "OfflineAssessmentResults" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Programmes_Code" ON "Programmes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProgrammeYears_ProgrammeId_YearNumber" ON "ProgrammeYears" ("ProgrammeId", "YearNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizAnswers_AttemptId" ON "QuizAnswers" ("AttemptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizAnswers_QuestionId" ON "QuizAnswers" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizAnswers_SelectedOptionId" ON "QuizAnswers" ("SelectedOptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizAttempts_QuizId" ON "QuizAttempts" ("QuizId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizAttempts_StudentId" ON "QuizAttempts" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizOptions_QuestionId" ON "QuizOptions" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_QuizQuestions_QuizId" ON "QuizQuestions" ("QuizId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_Quizzes_ModuleId" ON "Quizzes" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Semesters_ProgrammeYearId_SemesterNumber" ON "Semesters" ("ProgrammeYearId", "SemesterNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_StudentEnrolments_CohortId" ON "StudentEnrolments" ("CohortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_StudentEnrolments_StudentId" ON "StudentEnrolments" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_StudentEnrolments_UniversityId_CohortId" ON "StudentEnrolments" ("UniversityId", "CohortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StudentEnrolments_UniversityId_StudentId" ON "StudentEnrolments" ("UniversityId", "StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Students_UserId" ON "Students" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Universities_Domain" ON "Universities" ("Domain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE INDEX "IX_UniversityProgrammes_ProgrammeId" ON "UniversityProgrammes" ("ProgrammeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UniversityProgrammes_UniversityId_ProgrammeId" ON "UniversityProgrammes" ("UniversityId", "ProgrammeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705061153_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260705061153_InitialCreate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    ALTER TABLE "AspNetUsers" ADD "SupervisorId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "CalendarEvents" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "CohortId" uuid,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "StartAt" timestamp with time zone NOT NULL,
        "EndAt" timestamp with time zone NOT NULL,
        "EventType" integer NOT NULL,
        "RelatedModuleId" uuid,
        "RelatedRotationId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CalendarEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CalendarEvents_Cohorts_CohortId" FOREIGN KEY ("CohortId") REFERENCES "Cohorts" ("Id"),
        CONSTRAINT "FK_CalendarEvents_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "ContentVersions" (
        "Id" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "VersionNumber" integer NOT NULL,
        "BlobUrl" text NOT NULL,
        "Changelog" text,
        "Status" integer NOT NULL,
        "PublishedAt" timestamp with time zone,
        "ArchivedAt" timestamp with time zone,
        "CreatedByUserId" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ContentVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContentVersions_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "DiscussionThreads" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "LessonId" uuid NOT NULL,
        "Title" text NOT NULL,
        "CreatedByUserId" text NOT NULL,
        "IsLocked" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_DiscussionThreads" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DiscussionThreads_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DiscussionThreads_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "GradeSyncRequests" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "SemesterId" uuid NOT NULL,
        "CohortId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "RequestedByUserId" text NOT NULL,
        "ApprovedByUserId" text,
        "ApprovedAt" timestamp with time zone,
        "PushedAt" timestamp with time zone,
        "FailureReason" text,
        "RetryCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_GradeSyncRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GradeSyncRequests_Cohorts_CohortId" FOREIGN KEY ("CohortId") REFERENCES "Cohorts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GradeSyncRequests_Semesters_SemesterId" FOREIGN KEY ("SemesterId") REFERENCES "Semesters" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GradeSyncRequests_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "HospitalAttendanceFeeds" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "ExternalRecordId" text NOT NULL,
        "PayloadJson" text NOT NULL,
        "Status" integer NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL,
        "ProcessedAt" timestamp with time zone,
        "ErrorMessage" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_HospitalAttendanceFeeds" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HospitalAttendanceFeeds_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "HospitalDepartments" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "Name" text NOT NULL,
        "Code" text NOT NULL,
        "CapacityPerMonth" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_HospitalDepartments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HospitalDepartments_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "Notifications" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Type" text NOT NULL,
        "Title" text NOT NULL,
        "Body" text NOT NULL,
        "Channel" integer NOT NULL,
        "IsRead" boolean NOT NULL,
        "ReadAt" timestamp with time zone,
        "RelatedEntityType" text,
        "RelatedEntityId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "SisRosterSyncRuns" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "RecordsProcessed" integer NOT NULL,
        "RecordsAdded" integer NOT NULL,
        "RecordsUpdated" integer NOT NULL,
        "RecordsSuspended" integer NOT NULL,
        "ErrorMessage" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_SisRosterSyncRuns" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SisRosterSyncRuns_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "TenantIdpConfigs" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "ProviderType" integer NOT NULL,
        "MetadataUrl" text,
        "ClientId" text,
        "ClientSecretPlaceholder" text,
        "AuthorityUrl" text,
        "IsEnabled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_TenantIdpConfigs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TenantIdpConfigs_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "LiveClassSessions" (
        "Id" uuid NOT NULL,
        "CalendarEventId" uuid NOT NULL,
        "JoinUrl" text NOT NULL,
        "MinAttendanceMinutes" integer NOT NULL,
        "RecordingUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LiveClassSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LiveClassSessions_CalendarEvents_CalendarEventId" FOREIGN KEY ("CalendarEventId") REFERENCES "CalendarEvents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "AssessmentContentVersions" (
        "Id" uuid NOT NULL,
        "QuizId" uuid NOT NULL,
        "ContentVersionId" uuid NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_AssessmentContentVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentContentVersions_ContentVersions_ContentVersionId" FOREIGN KEY ("ContentVersionId") REFERENCES "ContentVersions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AssessmentContentVersions_Quizzes_QuizId" FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "DiscussionPosts" (
        "Id" uuid NOT NULL,
        "ThreadId" uuid NOT NULL,
        "Body" text NOT NULL,
        "CreatedByUserId" text NOT NULL,
        "ParentPostId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_DiscussionPosts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DiscussionPosts_DiscussionPosts_ParentPostId" FOREIGN KEY ("ParentPostId") REFERENCES "DiscussionPosts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DiscussionPosts_DiscussionThreads_ThreadId" FOREIGN KEY ("ThreadId") REFERENCES "DiscussionThreads" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "GradeSyncRecords" (
        "Id" uuid NOT NULL,
        "GradeSyncRequestId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "MarksJson" text NOT NULL,
        "SyncStatus" text NOT NULL,
        "ExternalReference" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_GradeSyncRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GradeSyncRecords_GradeSyncRequests_GradeSyncRequestId" FOREIGN KEY ("GradeSyncRequestId") REFERENCES "GradeSyncRequests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GradeSyncRecords_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "Rotations" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "HospitalDepartmentId" uuid NOT NULL,
        "CohortId" uuid NOT NULL,
        "Name" text NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "WeeksDuration" integer NOT NULL,
        "RequiredProcedureCount" integer NOT NULL,
        "RequiredAttendancePercent" numeric NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Rotations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rotations_Cohorts_CohortId" FOREIGN KEY ("CohortId") REFERENCES "Cohorts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Rotations_HospitalDepartments_HospitalDepartmentId" FOREIGN KEY ("HospitalDepartmentId") REFERENCES "HospitalDepartments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Rotations_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "Supervisors" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "HospitalDepartmentId" uuid NOT NULL,
        "Title" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Supervisors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Supervisors_HospitalDepartments_HospitalDepartmentId" FOREIGN KEY ("HospitalDepartmentId") REFERENCES "HospitalDepartments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Supervisors_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "SisRosterSyncRecords" (
        "Id" uuid NOT NULL,
        "SyncRunId" uuid NOT NULL,
        "ExternalStudentId" text NOT NULL,
        "Action" text NOT NULL,
        "StudentEmail" text NOT NULL,
        "AppliedAt" timestamp with time zone,
        "Details" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_SisRosterSyncRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SisRosterSyncRecords_SisRosterSyncRuns_SyncRunId" FOREIGN KEY ("SyncRunId") REFERENCES "SisRosterSyncRuns" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "RotationAssignments" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "RotationId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "AttendancePercent" numeric NOT NULL,
        "CompletedProcedureCount" integer NOT NULL,
        "CompletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_RotationAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RotationAssignments_Rotations_RotationId" FOREIGN KEY ("RotationId") REFERENCES "Rotations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RotationAssignments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RotationAssignments_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "SupervisorDelegations" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "SupervisorId" uuid NOT NULL,
        "DelegateSupervisorId" uuid NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_SupervisorDelegations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupervisorDelegations_Supervisors_DelegateSupervisorId" FOREIGN KEY ("DelegateSupervisorId") REFERENCES "Supervisors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SupervisorDelegations_Supervisors_SupervisorId" FOREIGN KEY ("SupervisorId") REFERENCES "Supervisors" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SupervisorDelegations_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "AttendanceRecords" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "RotationAssignmentId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "RecordDate" date NOT NULL,
        "Source" integer NOT NULL,
        "CheckInAt" timestamp with time zone,
        "CheckOutAt" timestamp with time zone,
        "DurationMinutes" integer NOT NULL,
        "FeedStatus" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AttendanceRecords_RotationAssignments_RotationAssignmentId" FOREIGN KEY ("RotationAssignmentId") REFERENCES "RotationAssignments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AttendanceRecords_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AttendanceRecords_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "LogbookEntries" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "RotationAssignmentId" uuid NOT NULL,
        "StudentId" uuid NOT NULL,
        "SupervisorId" uuid,
        "EntryDate" date NOT NULL,
        "Procedure" text NOT NULL,
        "PatientCount" integer NOT NULL,
        "Notes" text NOT NULL,
        "Location" text NOT NULL,
        "Status" integer NOT NULL,
        "SupervisorRemarks" text,
        "SubmittedAt" timestamp with time zone NOT NULL,
        "ReviewedAt" timestamp with time zone,
        "EscalatedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LogbookEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LogbookEntries_RotationAssignments_RotationAssignmentId" FOREIGN KEY ("RotationAssignmentId") REFERENCES "RotationAssignments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LogbookEntries_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LogbookEntries_Supervisors_SupervisorId" FOREIGN KEY ("SupervisorId") REFERENCES "Supervisors" ("Id"),
        CONSTRAINT "FK_LogbookEntries_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE TABLE "SignOffEscalations" (
        "Id" uuid NOT NULL,
        "UniversityId" uuid NOT NULL,
        "LogbookEntryId" uuid NOT NULL,
        "EscalatedToUserId" text NOT NULL,
        "EscalatedAt" timestamp with time zone NOT NULL,
        "Reason" text NOT NULL,
        "ResolvedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_SignOffEscalations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SignOffEscalations_LogbookEntries_LogbookEntryId" FOREIGN KEY ("LogbookEntryId") REFERENCES "LogbookEntries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SignOffEscalations_Universities_UniversityId" FOREIGN KEY ("UniversityId") REFERENCES "Universities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_AssessmentContentVersions_ContentVersionId" ON "AssessmentContentVersions" ("ContentVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_AssessmentContentVersions_QuizId_ContentVersionId" ON "AssessmentContentVersions" ("QuizId", "ContentVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_AttendanceRecords_RotationAssignmentId_RecordDate" ON "AttendanceRecords" ("RotationAssignmentId", "RecordDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_AttendanceRecords_StudentId" ON "AttendanceRecords" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_AttendanceRecords_UniversityId" ON "AttendanceRecords" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_CalendarEvents_CohortId" ON "CalendarEvents" ("CohortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_CalendarEvents_UniversityId" ON "CalendarEvents" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_ContentVersions_LessonId_VersionNumber" ON "ContentVersions" ("LessonId", "VersionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_DiscussionPosts_ParentPostId" ON "DiscussionPosts" ("ParentPostId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_DiscussionPosts_ThreadId" ON "DiscussionPosts" ("ThreadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_DiscussionThreads_LessonId" ON "DiscussionThreads" ("LessonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_DiscussionThreads_UniversityId" ON "DiscussionThreads" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_GradeSyncRecords_GradeSyncRequestId" ON "GradeSyncRecords" ("GradeSyncRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_GradeSyncRecords_StudentId" ON "GradeSyncRecords" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_GradeSyncRequests_CohortId" ON "GradeSyncRequests" ("CohortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_GradeSyncRequests_SemesterId" ON "GradeSyncRequests" ("SemesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_GradeSyncRequests_UniversityId" ON "GradeSyncRequests" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_HospitalAttendanceFeeds_UniversityId_ExternalRecordId" ON "HospitalAttendanceFeeds" ("UniversityId", "ExternalRecordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_HospitalDepartments_UniversityId_Code" ON "HospitalDepartments" ("UniversityId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_LiveClassSessions_CalendarEventId" ON "LiveClassSessions" ("CalendarEventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_LogbookEntries_RotationAssignmentId" ON "LogbookEntries" ("RotationAssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_LogbookEntries_StudentId" ON "LogbookEntries" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_LogbookEntries_SupervisorId" ON "LogbookEntries" ("SupervisorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_LogbookEntries_UniversityId" ON "LogbookEntries" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Notifications_UniversityId" ON "Notifications" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Notifications_UserId_IsRead" ON "Notifications" ("UserId", "IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_RotationAssignments_RotationId_StudentId" ON "RotationAssignments" ("RotationId", "StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_RotationAssignments_StudentId" ON "RotationAssignments" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_RotationAssignments_UniversityId" ON "RotationAssignments" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Rotations_CohortId" ON "Rotations" ("CohortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Rotations_HospitalDepartmentId" ON "Rotations" ("HospitalDepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Rotations_UniversityId" ON "Rotations" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_SignOffEscalations_LogbookEntryId" ON "SignOffEscalations" ("LogbookEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SignOffEscalations_UniversityId" ON "SignOffEscalations" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SisRosterSyncRecords_SyncRunId" ON "SisRosterSyncRecords" ("SyncRunId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SisRosterSyncRuns_UniversityId" ON "SisRosterSyncRuns" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SupervisorDelegations_DelegateSupervisorId" ON "SupervisorDelegations" ("DelegateSupervisorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SupervisorDelegations_SupervisorId" ON "SupervisorDelegations" ("SupervisorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_SupervisorDelegations_UniversityId" ON "SupervisorDelegations" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Supervisors_HospitalDepartmentId" ON "Supervisors" ("HospitalDepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE INDEX "IX_Supervisors_UniversityId" ON "Supervisors" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_Supervisors_UserId" ON "Supervisors" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    CREATE UNIQUE INDEX "IX_TenantIdpConfigs_UniversityId" ON "TenantIdpConfigs" ("UniversityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705070121_Phase2ClinicalAndIntegrations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260705070121_Phase2ClinicalAndIntegrations', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706093527_CertificateTemplate') THEN
    CREATE TABLE "CertificateTemplates" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "OrganizationName" character varying(200) NOT NULL,
        "Tagline" text NOT NULL,
        "AwardedToLabel" text NOT NULL,
        "BodyText" text NOT NULL,
        "DatePrefix" text NOT NULL,
        "Location" text NOT NULL,
        "FooterLocation" text NOT NULL,
        "WebsiteUrl" text NOT NULL,
        "LeftSignatoryTitle" text NOT NULL,
        "RightSignatoryTitle" text NOT NULL,
        "LogoUrl" text,
        "LeftSignatureImageUrl" text,
        "RightSignatureImageUrl" text,
        "PrimaryColor" text NOT NULL,
        "AccentColor" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CertificateTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706093527_CertificateTemplate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260706093527_CertificateTemplate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706102735_StudentSemesterProgress') THEN
    ALTER TABLE "StudentEnrolments" ADD "CurrentSemester" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706102735_StudentSemesterProgress') THEN
    ALTER TABLE "StudentEnrolments" ADD "CurrentYear" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706102735_StudentSemesterProgress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260706102735_StudentSemesterProgress', '10.0.9');
    END IF;
END $EF$;
COMMIT;

